pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Compile & Unit Test') {
            steps {
                sh './mvnw clean test' // Menjalankan tes dengan Testcontainers
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t irvansyah/taskmanager:${BUILD_NUMBER} .'
            }
        }
        stage('Security Scan') {
            steps {
                // Tahap opsional: tambahkan tools scan seperti SonarQube
                echo "Scanning for vulnerabilities..."
            }
        }
    }
    post {
        failure {
            echo "Pipeline gagal! Segera perbaiki unit test atau build."
        }
    }
}