pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Compile & Unit Test') {
            steps {
                // Diubah dari './mvnw' menjadi 'mvn' agar lebih stabil
                sh 'mvn clean test'
            }
        }
        stage('Docker Build') {
            steps {
                // Diubah: Perintah docker build biasanya menggunakan '.' (titik)
                // untuk konteks folder saat ini, bukan '.mvn'
                sh 'docker build -t irvansyah/taskmanager:${BUILD_NUMBER} .'
            }
        }
        stage('Security Scan') {
            steps {
                echo "Scanning for vulnerabilities..."
            }
        }
    }
    post {
        failure {
            echo "Pipeline gagal! Segera perbaiki unit test atau build."
        }
    }
}